#pragma once

#include "Spake2p.h"
#include "common/Cache.h"

/**
 * Fake salt to avoid attackers from probing valid usernames.
 * The cache given to each invalid username should stay the same so the 
 * attacker cannot tell a valid username from an invalid one w/o knowning the password.
 * The fake cache is generated by HKDF(_fakeSaltPrk, username)
 * Also fake w0 and L to be valid Ed25519 scalars and points.
 * So the calculation time won't vary for valid and invalid usernames.
 * w0 and L does not need to be stable for the same username.
 */

namespace TUI::Cipher
{
    class FakeCredentialGenerator
    {
    public:
        static constexpr size_t SALT_PRK_SIZE = 32;

        explicit FakeCredentialGenerator(size_t cacheSize);
        Spake2p::RegistrationResult GetFakeCredential(const std::string& username);
    private:
        Common::Cache<std::string, Spake2p::RegistrationResult> _cache;
        std::array<uint8_t, SALT_PRK_SIZE> _saltPrk;
    };
}
